name: "Playright to Slack"
description: "Publish playwright results to Slack"
branding:
  icon: "award"
  color: "green"
inputs:
  filePath:
    description: "Playwright json file"
    required: false
    default: "./playwright-report/test-results.json"
  slackToken:
    description: "Github token of the repository (automatically created by Github)"
    required: true
  channel:
    description: "Slack channel name"
    required: true
  environment:
    description: "Testing environment"
    required: false
    default: ""
runs:
  using: "node16"
  main: "index.js"
